"""Generate public test vectors with the actual BLAKE2b SeedSigner signing code.

Run with SeedSigner's src on PYTHONPATH and its pinned embit installed.
Uses the public BIP39 abandon/about test mnemonic; never fund these keys.
"""
import base64
import json
from pathlib import Path
from embit import bip32, script, ec
from embit.psbt import PSBT, DerivationPath
from embit.transaction import Transaction, TransactionInput, TransactionOutput
from seedsigner.models.seed import Seed
from seedsigner.models.psbt_parser import PSBTParser
from seedsigner.models.encode_qr import UrPsbtQrEncoder
from seedsigner.models.settings import SettingsConstants

seed = Seed(mnemonic=("abandon " * 11 + "about").split())
root = bip32.HDKey.from_seed(seed.seed_bytes)
fixtures = []
for name, purpose in [("legacy", 44), ("nested", 49), ("segwit", 84), ("taproot", 86)]:
    account_path = f"m/{purpose}h/0h/0h"
    path = bip32.parse_path(account_path + "/0/0")
    child = root.derive(path)
    pub = child.key.get_public_key()
    spk = {"legacy": script.p2pkh, "nested": lambda p: script.p2sh(script.p2wpkh(p)),
           "segwit": script.p2wpkh, "taproot": script.p2tr}[name](pub)
    parent = Transaction(vin=[TransactionInput(bytes.fromhex("11" * 32), 0)], vout=[TransactionOutput(100000, spk)])
    tx = Transaction(vin=[TransactionInput(parent.txid(), 0, sequence=0xfffffffd)],
                     vout=[TransactionOutput(98000, script.p2wpkh(ec.PrivateKey(bytes.fromhex("22" * 32)).get_public_key()))])
    request = PSBT(tx)
    inp = request.inputs[0]
    inp.non_witness_utxo = parent
    if name != "legacy": inp.witness_utxo = parent.vout[0]
    if name == "nested": inp.redeem_script = script.p2wpkh(pub)
    if name == "taproot":
        inp.taproot_internal_key = pub
        inp.taproot_bip32_derivations[pub] = ([], DerivationPath(root.my_fingerprint, path))
    else: inp.bip32_derivations[pub] = DerivationPath(root.my_fingerprint, path)
    inp.sighash_type = 0x21
    unsigned = request.serialize()
    shown, reason = PSBTParser.screen_sighash_type(request, seed, SettingsConstants.MAINNET)
    assert shown == 0x21, reason
    assert request.sign_with(root, sighash=PSBTParser.sighash_type(request)) == 1
    signed = PSBTParser.trim(request)
    encoder = UrPsbtQrEncoder(psbt=signed, qr_density=SettingsConstants.DENSITY__LOW)
    # Include redundant fountain frames to test out-of-order decoding.
    frames = [encoder.next_part() for _ in range(encoder.seq_len() * 3)]
    account = root.derive(account_path).to_public()
    fixtures.append(dict(script=name, public_key=f"[{root.my_fingerprint.hex()}{account_path[1:]}]{account.to_base58()}",
        receive_address=spk.address(), original=base64.b64encode(unsigned).decode(),
        signed=base64.b64encode(signed.serialize()).decode(), ur=frames))
Path("mobile/Tests/PaperclipMobileTests/Fixtures/seedsigner.json").write_text(json.dumps(fixtures, indent=2) + "\n")

# Optional: requests generated by the Rust BDK unit test, for a complete host/signer round trip.
import os
if path := os.environ.get("PAPERCLIP_HARDWARE_FIXTURES"):
    actual = json.loads(Path(path).read_text())
    for item in actual:
        psbt = PSBT.parse(base64.b64decode(item["original"]))
        shown, reason = PSBTParser.screen_sighash_type(psbt, seed, SettingsConstants.MAINNET)
        assert shown == 0x21, reason
        assert psbt.sign_with(root, sighash=PSBTParser.sighash_type(psbt)) == len(psbt.inputs)
        item["signed"] = base64.b64encode(PSBTParser.trim(psbt).serialize()).decode()
    Path("mobile/Tests/PaperclipMobileTests/Fixtures/bdk-seedsigner.json").write_text(json.dumps(actual, indent=2) + "\n")
